""""Add_fields_to_Project_model"

Revision ID: 2ecd98d24e84
Revises: 8ffc8f436f1a
Create Date: 2025-07-04 19:05:21.365423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ecd98d24e84'
down_revision: Union[str, Sequence[str], None] = '8ffc8f436f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('skrot', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('rodzaj', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('uwagi', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'uwagi')
    op.drop_column('projects', 'rodzaj')
    op.drop_column('projects', 'skrot')
    # ### end Alembic commands ###
