""""Add_UnitPrice_model"

Revision ID: 4557a451eaf4
Revises: 56d42875e05f
Create Date: 2025-07-05 10:26:04.923479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4557a451eaf4'
down_revision: Union[str, Sequence[str], None] = '56d42875e05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa_roboty', sa.String(length=255), nullable=False),
    sa.Column('jednostka_miary', sa.String(length=50), nullable=False),
    sa.Column('cena_jednostkowa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_oferty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_oferty'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_prices')
    # ### end Alembic commands ###
