"""Add Project model and link to Tender

Revision ID: 8ffc8f436f1a
Revises: ddf7530f9af4
Create Date: 2025-07-04 08:54:49.198560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ffc8f436f1a'
down_revision: Union[str, Sequence[str], None] = 'ddf7530f9af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa_projektu', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazwa_projektu')
    )
    op.add_column('tenders', sa.Column('id_projektu', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_tenders_projects', 'tenders', 'projects', ['id_projektu'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tenders_projects', 'tenders', type_='foreignkey')
    op.drop_column('tenders', 'id_projektu')
    op.drop_table('projects')
    # ### end Alembic commands ###
