"""Allow null id_kategorii in WorkType

Revision ID: a143b97b3348
Revises: 6d0c856eb635
Create Date: 2025-07-09 21:48:50.109141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a143b97b3348'
down_revision: Union[str, Sequence[str], None] = '6d0c856eb635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_types', 'id_kategorii',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_types', 'id_kategorii',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###