""""Add_Category_and_update_UnitPrice"

Revision ID: c801b5b50ecc
Revises: 4557a451eaf4
Create Date: 2025-07-05 10:36:36.209705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c801b5b50ecc'
down_revision: Union[str, Sequence[str], None] = '4557a451eaf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa_kategorii', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazwa_kategorii')
    )
    op.add_column('unit_prices', sa.Column('id_kategorii', sa.Integer(), nullable=True))
    op.add_column('unit_prices', sa.Column('uwagi', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'unit_prices', 'categories', ['id_kategorii'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit_prices', type_='foreignkey')
    op.drop_column('unit_prices', 'uwagi')
    op.drop_column('unit_prices', 'id_kategorii')
    op.drop_table('categories')
    # ### end Alembic commands ###
