"""Add Tender model

Revision ID: ddf7530f9af4
Revises: 86c8329a3698
Create Date: 2025-07-04 08:20:22.538989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf7530f9af4'
down_revision: Union[str, Sequence[str], None] = '86c8329a3698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa_oferty', sa.String(length=255), nullable=False),
    sa.Column('data_otrzymania', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('id_firmy', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_firmy'], ['firmy.id_firmy'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenders')
    # ### end Alembic commands ###
